apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperclip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/forward0666/devop-admin.git
    targetRevision: HEAD
    path: paperclip
  destination:
    server: https://kubernetes.default.svc
    namespace: paperclip
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
