apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secret.BETTER_AUTH_SECRET | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
